add test

diff --git a/.github/workflows/deploy-and-test-cluster.yml b/.github/workflows/deploy-and-test-cluster.yml
--- a/.github/workflows/deploy-and-test-cluster.yml
+++ b/.github/workflows/deploy-and-test-cluster.yml
@@ -115,7 +115,7 @@ jobs:
             echo "Listing all pods in default namespace:"
             kubectl get pods -n default
           fi      
-          
+
   deploy-app-with-helm:
     runs-on: ubuntu-latest
     needs: deploy-app-with-kubectl
@@ -138,7 +138,7 @@ jobs:
           DOCKER_USER: ${{ vars.DOCKER_USER }}
           APPLICATION_NAME: ${{ inputs.application-name }}
         run: |
-          echo "Pulling Helm Chart Version: $HELM_CHART_VERSION from oci://registry-1.docker.io/$DOCKER_USER/$APPLICATION_NAME"
+          echo "Pulling Helm Chart Version: $HELM_CHART_VERSION"
           helm pull oci://registry-1.docker.io/$DOCKER_USER/$APPLICATION_NAME --version "$HELM_CHART_VERSION"
           tar -xvf $APPLICATION_NAME-*.tgz  
 
@@ -149,7 +149,7 @@ jobs:
           NAMESPACE: ${{ inputs.namespace }}
         run: |
           # Install/upgrade the Helm chart
-          echo "Deploying Application $APPLICATION_NAME: $APP_VERSION"
+          echo "Deploying Application: $APP_VERSION"
           helm upgrade --install $APPLICATION_NAME ./$APPLICATION_NAME \
           --set image.tag=${APP_VERSION} \
           --namespace ${NAMESPACE} \
@@ -162,7 +162,7 @@ jobs:
           NAMESPACE: ${{ inputs.namespace }}
           APPLICATION_NAME: ${{ inputs.application-name }}
         run: |
-          if ! kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=$APPLICATION_NAME -n $NAMESPACE --timeout=240s; then
+          if ! kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=$APPLICATION_NAME -n $NAMESPACE --timeout=180s; then
             POD_NAME=$(kubectl get pods -l app.kubernetes.io/name=$APPLICATION_NAME -o jsonpath="{.items[0].metadata.name}" -n $NAMESPACE)
             kubectl logs $POD_NAME -n $NAMESPACE
             echo "Describing the pod:"
@@ -172,6 +172,37 @@ jobs:
           BUILD_LINK="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.deployed-by-build }}"
           echo "::notice:: ### Helm Deployed Version: ${{ inputs.version }}"
           echo "::notice:: ### Deployment triggered by workflow ${{ inputs.deployed-by-workflow }}. Run number: ${{ inputs.deployed-by-build }}: $BUILD_LINK"
+
+      - name: Test Application
+        env:
+          APP_VERSION: ${{ inputs.version }}
+          APPLICATION_NAME: ${{ inputs.application-name }}
+          NAMESPACE: ${{ inputs.namespace }}
+        run: |
+          echo "::group::Application Deployment Status"
+          echo "Checking status of $APPLICATION_NAME (version $APP_VERSION) in namespace $NAMESPACE"
+          echo "Helm Release Details:"
+          helm status $APPLICATION_NAME --namespace ${NAMESPACE}
+          echo "::endgroup::"
+          
+          echo "::group::Helm Test Raw Output"
+          echo "Testing Application $APPLICATION_NAME: $APP_VERSION"
+          TEST_OUTPUT=$(helm test $APPLICATION_NAME --namespace ${NAMESPACE} --logs)
+          TEST_EXIT_CODE=$?
+          echo "Exit Code: $TEST_EXIT_CODE"
+          echo "$TEST_OUTPUT"
+          echo "::endgroup::"
+          
+          # Check all test exit codes
+          if echo "$TEST_OUTPUT" | grep -q "Exit code: [^0]"; then
+            echo "::error::One or more Helm tests failed. See details above:"
+            exit 1
+          elif [ $TEST_EXIT_CODE -ne 0 ]; then
+            echo "::error::Helm test command failed with exit code $TEST_EXIT_CODE"
+            exit $TEST_EXIT_CODE
+          else
+            echo "All Helm tests passed successfully."
+          fi      
 
       - name: Display Deployment Information
         env:
